// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    // TopNav: typeof import('./src/components/TopNav/TopNav.vue')['default']
    // VanButton: typeof import('vant/es')['Button']
    // VanCol: typeof import('vant/es')['Col']
    // VanIcon: typeof import('vant/es')['Icon']
    // VanImage: typeof import('vant/es')['Image']
    // VanPopup: typeof import('vant/es')['Popup']
    // VanProgress: typeof import('vant/es')['Progress']
    // VanRow: typeof import('vant/es')['Row']
    // VanSticky: typeof import('vant/es')['Sticky']
  }
}
